version: '2'

services:
  db:
    image: postgres
  web:
    build: .
    #command: python3 manage.py runserver 0.0.0.0:8000
    command: gunicorn pathwayserv.wsgi
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
