# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-11 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='bounding_box',
        ),
        migrations.RemoveField(
            model_name='route',
            name='center_lat',
        ),
        migrations.RemoveField(
            model_name='route',
            name='center_long',
        ),
        migrations.AlterField(
            model_name='route',
            name='atype',
            field=models.CharField(choices=[('W', 'Walking'), ('B', 'Biking'), ('R', 'Running')], default='W', max_length=1),
        ),
    ]
