# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 03:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='atype',
            field=models.CharField(choices=[('B', 'Biking'), ('W', 'Walking'), ('R', 'Running')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.Pword'),
        ),
    ]
