# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171107_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password_id',
        ),
        migrations.AlterField(
            model_name='route',
            name='atype',
            field=models.CharField(choices=[('R', 'Running'), ('W', 'Walking'), ('B', 'Biking')], default='W', max_length=1),
        ),
    ]
