# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-07 03:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20171107_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='bounding_box',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
